### ISSUE TITLE
django-markupfield does not currently support Django 1.7 migrations

### ISSUE THREAD

**Issue by Matt3o12** [jamesturk/django-markupfield#20]
When migrating a model with Django 1.7b3, I end up getting the error message:

`django.db.utils.OperationalError: duplicate column name: desc_markup_type`

models.py
 
    class Project(models.Model):
        name = models.CharField(max_length=80)
        desc = MarkupField(escape_html = True, null=True)

0001_initial.py

    class Migration(migrations.Migration):

        dependencies = [
        ]

        operations = [
            migrations.CreateModel(
                name=b'Project',
                fields=[
                    ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                    (b'name', models.CharField(max_length=80)),
                    (b'desc', markupfield.fields.MarkupField(null=True)),
                    (b'desc_markup_type', models.CharField(default=None, max_length=30, choices=[(b'', b'--'), (b'html', b'html'), (b'plain', b'plain')])),
                    (b'_desc_rendered', models.TextField(editable=False)),
                ],
                options={
                },
                bases=(models.Model,),
            ),
        ]

Quick-fix: You can temporarily fix this issue by commenting you b'desc_markup_type and _desc_rendered in the `Migration` class. Updating a model that way won't work, though (unless you don't mind removing the whole MarkupField temporally).

**Comment by rserrano** [comment]
Good afternoon. I'm trying to use MarkupField but it fails when executing migrate in django 1.7. Is it fixed?

class HelpText(db.models.Model):
    topic = db.models.ForeignKey(Topic)
    country_code   = db.models.CharField(max_length=5, verbose_name=_("Language"), null=False, blank=False)
    name_trans = db.models.CharField(max_length=40, verbose_name=_("Name"), null=False, blank=False)
    body  = MarkupField()
    # db.models.TextField(verbose_name=_("Help Text")) 
    class Meta:
        unique_together = (('topic', 'country_code'), )


  Applying help.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 36, in database_forwards
    schema_editor.create_model(model)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 262, in create_model
    self.execute(sql, params)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 103, in execute
    cursor.execute(sql, params)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ricardo/dev/prototype/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: duplicate column name: body_markup_type

**Comment by rserrano** [comment]
pip list
argparse (1.2.1)
Django (1.7.3)
django-markupfield (1.2.1)
docutils (0.12)
geo-model (0.1)
Markdown (2.5.2)
numpy (1.9.1)
Pillow (2.7.0)
pip (1.5.6)
scipy (0.14.0)
setuptools (11.3.1)
Shapely (1.5.0)
simplejson (3.6.5)
wsgiref (0.1.2)

**Comment by jamesturk** [comment]
no unfortunately I don't think this will be ported to work with 1.7.

**Comment by savingschampion** [comment]
rserrano if you read the traceback, it appears you already have a column called body_markup_type.

also SQLITE is not the best DB to use with Django

**Comment by jamesturk** [comment]
PR https://github.com/jamesturk/django-markupfield/pull/29 should have this squared away- need to add some tests but it is reportedly working now
